spring:
  application:
    name: discodeit
  jpa:
    hibernate:
      ddl-auto: none  # Entity를 보고 Table 자동 생성 여부 설정
    open-in-view: false
  profiles:
    active: dev

discodeit:
  storage: # 파일 저장소 관련 설정
    type: local
    local:
      root-path: ./storage/binary

logging:
  level:
    root: INFO # 전체 로그 레벨 설정
